#!/bin/bash

fogvalues(){
##Version
#debian
sed -n 3p /etc/os-release > /etc/xdeb1
cat  "/etc/xdeb1" | cut -d "=" -f2 > /etc/xdeb2
cat /etc/xdeb2 |grep -Eo "[0-9]+" > /etc/xdeb3
#ubuntu
sed -n 6p /etc/os-release > /etc/xub1
cat  "/etc/xub1" | cut -d "=" -f2 > /etc/xub2
cat /etc/xub2 |grep -Eo "[0-9]+" > /etc/xub3
sed -n 1p /etc/xub3 > /etc/xub4
## OS:
#debian
sed -n 6p /etc/os-release > /etc/xxdeb1
cat  "/etc/xxdeb1" | cut -d "=" -f2 > /etc/xxdeb2
#ubuntu
sed -n 3p /etc/os-release > /etc/xxub1
cat  "/etc/xxub1" | cut -d "=" -f2 > /etc/xxub2
}


fogdebian(){
fogdebid=$(cat /etc/xxdeb2)
fogdebver=$(cat /etc/xdeb3)
if [[ "$fogdebid" == 'debian' ]];then
installdebian
exit
fi
}
installdebian(){
if [[ "$fogdebver" -le 10 ]];then
wget https://github.com/korn-sudo/Project-Fog/raw/main/files/installer/deb255 && chmod +x ./deb255 && ./deb255
else
wget https://github.com/korn-sudo/Project-Fog/raw/main/files/installer/deb256 && chmod +x ./deb256 && ./deb256
fi
}


fogubuntu(){
fogubid=$(cat /etc/xxub2)
fogubver=$(cat /etc/xub4)
if [[ "$fogubid" == 'ubuntu' ]];then
installubuntu
exit
fi
}
installubuntu(){
if [[ "$fogubver" -le 18 ]] ;then
 wget https://github.com/korn-sudo/Project-Fog/raw/main/files/installer/ub255 && chmod +x ./ub255 && ./ub255
else
 wget https://github.com/korn-sudo/Project-Fog/raw/main/files/installer/ub256 && chmod +x ./ub256 && ./ub256
fi
}


fogvalues
fogdebian
fogubuntu
exit


